Make types Send and Sync where applicable
kenba/opencl3 pull request #6
Opened 2021-03-08 12:02 UTC by vmx

All operations in OpenCL, except a few on kernels are thread-safe, see
https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_multiple_host_threads

Hence it's safe to implement `Send` and `Sync` for all of them, except for
`Kernel`. There only `Send` is implemented as it is still safe to move it
between threads, only concurrent access is a problem.

Currently the shared virtual memory types don't implement `Sync`, although
they theoretically could. The reason is that they currently have in internal
reference to the `Context` type, which contains `Kernel`s, which are not
`Sync`. This could be changed by only storing the `cl_context` instead of
a full `Context` reference within the shared virtual memory types.

Please note that I'm new to OpenCL so please review this PR carefully, I might
have missed things.

2021-03-09 20:18 UTC, kenba requested changes
Thank you for considering concurrency and implementing these functions.  
However, just because you can do something doesn't mean that you *should* do it...

The purpose behind most of the `opencl3` objects is to implement RAII on the object types.  
Some of the other objects, such as `Device` simply group together functions that correspond to real world `opencl` objects. In the particular case of `Device` and `Platform`, they are only used to create a `Context`.

I recommend that you read [OpenCL description](https://github.com/kenba/opencl3/blob/main/docs/opencl_description.md) to understand my view of how `OpenCL` works.

There may be a valid use case for adding `Send` and possibly `Sync` traits to some of the structs. However, since most (if not all!) of them are `read only` after construction, `Send` and `Sync` are not required.

Please consider whether it makes sense to implement `Send` and `Sync` for each type and remove those for which it does not.

2021-03-09 21:18 UTC, vmx commented
Thanks for the review. This PR was triggered by a real world use case. I'm currently porting code from `ocl` to `opencl3`. Which is the reason you're seeing a few PRs from me. I'm adding the missing pieces I need.

While I was adding `Sync` and `Send` to some of the types, I thought that according to the OpenCL spec most things are thread save, I add `Sync` to all thread safe ones and `Send` to all of them.

But yes, that might be the wrong approach, so I'm happy to apply them only to the types I need for my use case. These are:

 - `Sync`:
   - `Platform` and `Device`: Reason is that they are both initialized through a lazy static once. Lazy static requires them to be `Sync`. Given how they work (at least how I understand them), I think it's reasonable to have them `Sync`.
 - `Send`:
   - `Device` and `Context`: Reason is that the execution happens in a thread pool. This is where you need a `Send` implementation.

Though if `Send` is implemented for `Context` I think it should also be implemented for all the types it wraps, else it would sound wrong to me.

2021-03-09 21:59 UTC, vmx commented
I just realized, I need to take a closer look at the actual code. I wonder if using a thread pool actually makes sense. It could be that it was inherited by a previous non-GPU version where it made sense. I'll comment on the `Send` part at a later point again, the `Sync` part is still valid though.

2021-03-10 12:01 UTC, vmx commented
The use case for having `Send` is if you want to do scheduling across multiple GPUs manually. With `Send` you can prepare separate kernels for each device and then run them in parallel in dedicated threads.

2021-03-22 14:06 UTC, vmx commented
Discussion has moved to #9, hence closing this one.

2021-03-22 14:06 UTC, closed without merging